[theme]
base = "light"  # 'light' or 'dark' theme base
primaryColor = "#A3A9A9"  # Main color of the app
backgroundColor = "#FFFFFF"  # Background color of the app
secondaryBackgroundColor = "#fff4e4"  # Secondary background color, for areas like sidebar
font = "monospace"  # Font type for text, options include 'sans-serif', 'serif', 'monospace'
